Crypto227/Models/Coin.cs
using Crypto227.Supporters;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Crypto227.Models
{
    /// <summary>
    ///  RAW and DISPLAY details will be saved as keys
    /// </summary>
    public class Coin
    {
        [JsonConverter(typeof(CoinConverter))]
        public Dictionary<string, DataType> DataTypes { get; set; }

        public Coin()
        {
            DataTypes = new Dictionary<string, DataType>();
        }
    }

    /// <summary>
    /// BTC and other coins 
    /// </summary>
    public class DataType
    {
        public  Dictionary<string, CoinType> CoinTypes { get; set; }

        public DataType()
        {
            CoinTypes = new Dictionary<string, CoinType>();
        }
    }

    public class CoinType
    {
        public Dictionary<string, Dictionary<string,string>> Currencies { get; set; }

        public CoinType()
        {
            Currencies = new Dictionary<string, Dictionary<string, string>>();
        }
    }

    public class CoinListByVolume
    {
        [JsonProperty("Data")]
        public List<CoinListByVolumeDetails> Data { get; set; }
    }
    public partial class CoinListByVolumeDetails
    {
        [JsonProperty("SYMBOL")]
        public string Symbol { get; set; }

        [JsonProperty("SUPPLY")]
        public double Supply { get; set; }

        [JsonProperty("FULLNAME")]
        public string Fullname { get; set; }

        [JsonProperty("NAME")]
        public string Name { get; set; }

        [JsonProperty("ID")]
        public string Id { get; set; }

        [JsonProperty("VOLUME24HOURTO")]
        public double Volume24Hourto { get; set; }
    }
    public class CoinMain
    {
        public Coin CoinHeader { get; set; }
        public CoinListByVolume CoinDetialByVolume { get; set; }
    }
}

Crypto227/Models/ErrorViewModel.cs
using System;

namespace Crypto227.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Crypto227/Controllers/CoinListController.cs
using System;
using System.Net.Http;
using System.Threading.Tasks;
using Crypto227.Models;
using Crypto227.Supporters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;

namespace Crypto227.Controllers
{
    public class CoinListController : Controller
    {
        public string CoinTypes { get; }

        public string CurrencyTypes { get; }

        public string CryptoCompareUrl { get; set; }

        public CoinListController(IConfiguration configuration)
        {
            CoinTypes = configuration.GetSection("ApplicationSettings").GetSection("CoinTypes").Value;
            CurrencyTypes = configuration.GetSection("ApplicationSettings").GetSection("CurrencyTypes").Value;
            CryptoCompareUrl = configuration.GetSection("ApplicationSettings").GetSection("CryptoCompareUrl").Value;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> GetData()
        {
            var coinDetails = await CoinService.GetCoinDetails(CoinTypes, CurrencyTypes, CryptoCompareUrl);
            return  PartialView("_CoinWidgetPartial", coinDetails);
        }

        [HttpGet]
        public async Task<IActionResult> GetCoinListByVolumne()
        {
            var coinDetails = await CoinService.GetCoinDetailsByVolume("BTC", CryptoCompareUrl);
            return PartialView("_CoinListByVolume", coinDetails);
        }
    }
}

Crypto227/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Crypto227.Models;
using System.Net.Http;
using Newtonsoft.Json;
using Crypto227.Supporters;
using Microsoft.Extensions.Configuration;

namespace Crypto227.Controllers
{
    public class HomeController : Controller
    {
        public string CoinTypes { get; }

        public string CurrencyTypes { get; }

        public string CryptoCompareUrl { get; set; }

        public HomeController(IConfiguration configuration)
        {
            CoinTypes = configuration.GetSection("ApplicationSettings").GetSection("CoinTypes").Value;
            CurrencyTypes = configuration.GetSection("ApplicationSettings").GetSection("CurrencyTypes").Value;
            CryptoCompareUrl = configuration.GetSection("ApplicationSettings").GetSection("CryptoCompareUrl").Value;
        }

        public async Task<IActionResult> Index()
        {
            var coinMain = new CoinMain();
            coinMain.CoinHeader = await CoinService.GetCoinDetails(CoinTypes, CurrencyTypes, CryptoCompareUrl);
            coinMain.CoinDetialByVolume = await CoinService.GetCoinDetailsByVolume("BTC", CryptoCompareUrl);
            return View("Index", coinMain);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Crypto227/Views/CoinList/Index.cshtml
@{
    ViewData["Title"] = "Crypto Coin Details";
    ViewData["SubTitle"] = "Crypto Coin Details";
}

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-header" data-background-color="purple">
                <h4 class="title">Simple Table</h4>
                <p class="category">Here is a subtitle for this table</p>
            </div>
            <div class="card-content table-responsive">
                <table class="table">
                    <thead class="text-primary">
                    <th>Name</th>
                    <th>Country</th>
                    <th>City</th>
                    <th>Salary</th>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Dakota Rice</td>
                            <td>Niger</td>
                            <td>Oud-Turnhout</td>
                            <td class="text-primary">$36,738</td>
                        </tr>
                        <tr>
                            <td>Minerva Hooper</td>
                            <td>Curaçao</td>
                            <td>Sinaai-Waas</td>
                            <td class="text-primary">$23,789</td>
                        </tr>
                        <tr>
                            <td>Sage Rodriguez</td>
                            <td>Netherlands</td>
                            <td>Baileux</td>
                            <td class="text-primary">$56,142</td>
                        </tr>
                        <tr>
                            <td>Philip Chaney</td>
                            <td>Korea, South</td>
                            <td>Overland Park</td>
                            <td class="text-primary">$38,735</td>
                        </tr>
                        <tr>
                            <td>Doris Greene</td>
                            <td>Malawi</td>
                            <td>Feldkirchen in Kärnten</td>
                            <td class="text-primary">$63,542</td>
                        </tr>
                        <tr>
                            <td>Mason Porter</td>
                            <td>Chile</td>
                            <td>Gloucester</td>
                            <td class="text-primary">$78,615</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-md-12">
        <div class="card card-plain">
            <div class="card-header" data-background-color="purple">
                <h4 class="title">Table on Plain Background</h4>
                <p class="category">Here is a subtitle for this table</p>
            </div>
            <div class="card-content table-responsive">
                <table class="table table-hover">
                    <thead>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Salary</th>
                    <th>Country</th>
                    <th>City</th>
                    </thead>
                    <tbody>
                        <tr>
                            <td>1</td>
                            <td>Dakota Rice</td>
                            <td>$36,738</td>
                            <td>Niger</td>
                            <td>Oud-Turnhout</td>
                        </tr>
                        <tr>
                            <td>2</td>
                            <td>Minerva Hooper</td>
                            <td>$23,789</td>
                            <td>Curaçao</td>
                            <td>Sinaai-Waas</td>
                        </tr>
                        <tr>
                            <td>3</td>
                            <td>Sage Rodriguez</td>
                            <td>$56,142</td>
                            <td>Netherlands</td>
                            <td>Baileux</td>
                        </tr>
                        <tr>
                            <td>4</td>
                            <td>Philip Chaney</td>
                            <td>$38,735</td>
                            <td>Korea, South</td>
                            <td>Overland Park</td>
                        </tr>
                        <tr>
                            <td>5</td>
                            <td>Doris Greene</td>
                            <td>$63,542</td>
                            <td>Malawi</td>
                            <td>Feldkirchen in Kärnten</td>
                        </tr>
                        <tr>
                            <td>6</td>
                            <td>Mason Porter</td>
                            <td>$78,615</td>
                            <td>Chile</td>
                            <td>Gloucester</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Crypto227/Views/CoinList/_CoinWidgetPartial.cshtml
@model Coin
<div>
    
    @{
        var display = Model.DataTypes.FirstOrDefault(x => x.Key.Equals("DISPLAY", StringComparison.OrdinalIgnoreCase));

        foreach (var coinType in display.Value.CoinTypes)
        {
            var coinName = coinType.Key;
            var usdCurrency = coinType.Value.Currencies.FirstOrDefault(x=> x.Key.Equals("USD")).Value;

           <div class="col-lg-2 col-md-2 col-sm-2">
               <div class="card card-stats">
                   <div class="card-header" data-background-color="blue">
                        <p class="category">
                            @coinName
                        </p>
                   </div>
                   <div class="card-content">
                      
                       <p class="title price">
                           @usdCurrency["PRICE"]
                       </p>
                       <p class="title percentage">
                           (@usdCurrency["CHANGEPCT24HOUR"]%)
                       </p>
                   </div>
                   <div class="card-footer">
                       <div class="stats">
                           <i class="material-icons">update</i>   @usdCurrency["LASTUPDATE"]
                           <i>from  @usdCurrency["LASTMARKET"]</i>
                       </div>
                   </div>
               </div>
           </div>
         }
    }
</div>

Crypto227/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Crypto227/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Crypto227/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Dashboard";
    ViewData["SubTitle"] = " Material Dashboard";
}
@model CoinMain
<div class="row" id="HighRatedList">
    @Html.Partial("~/Views/CoinList/_CoinWidgetPartial.cshtml", @Model.CoinHeader)
</div>
<div class="row">
    <div class="col-lg-12 col-md-12" id="ListByVolume">
            @Html.Partial("~/Views/CoinList/_CoinListByVolume.cshtml", @Model.CoinDetialByVolume)
    </div>
</div>

@section Scripts{
    <script type="text/javascript">
        $(function () {
           
            // On initial load
            $(".percentage:contains('-')").removeClass('text-success').addClass('text-danger');
            $('.percentage:not(:contains("-"))').removeClass('text-danger').addClass('text-success');

            setInterval(function () {
                $("#HighRatedList").load("@Url.Action("GetData", "CoinList")", function (text, status, xhr) {
                    $(".percentage:contains('-')").removeClass('text-success').addClass('text-danger');
                    $('.percentage:not(:contains("-"))').removeClass('text-danger').addClass('text-success');
                });
            }, 2000);

            setInterval(function () {
                $("#ListByVolume").load("@Url.Action("GetCoinListByVolumne", "CoinList")", function (text, status, xhr) {
                });
            }, 10000);
        });
    </script>
}

Crypto227/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <title>@ViewData["Title"] - Crypto227</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
        <link href="~/lib/material/dist/css/material-dashboard.css" rel="stylesheet" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" type="text/css" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300|Material+Icons' rel='stylesheet' type='text/css'>
</head>
<body>
    <div class="wrapper">
        <div>
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                </div>
            </div>
            <footer class="footer">
                <div class="container-fluid">
                    <nav class="pull-left">
                        <ul>
                            <li>
                                <a href="#">
                                    Home
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Company
                                </a>
                            </li>
                            <li>
                                <a href="#">
                                    Portfolio
                                </a>
                            </li>
                        </ul>
                    </nav>
                    <p class="copyright pull-right">
                        &copy;
                        <script>
                            document.write(new Date().getFullYear())
                        </script>
                        <a href="/">A7P</a>, love development
                    </p>
                </div>
            </footer>
            <environment include="Development">
                <script src="~/lib/jquery/dist/jquery.js"></script>
                <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
                <script src="~/lib/material/dist/js/material.min.js"></script>
                <script src="~/js/chartist.min.js"></script>
                <script src="~/js/arrive.min.js"></script>
                <script src="~/js/perfect-scrollbar.jquery.min.js"></script>
                <script src="~/js/bootstrap-notify.js"></script>
                <script src="~/js/material-dashboard.js?v=1.2.0"></script>
                <script src="~/js/common.js" asp-append-version="true"></script>
                @*<script src="~/js/site.js" asp-append-version="true"></script>*@
                <script type="text/javascript">
                    $(document).ready(function () {
                        //demo.initDashboardPageCharts();
                        $('.dropdown-toggle').dropdown();
                    });
                </script>
            </environment>
            <environment exclude="Development">
                <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                        asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                        asp-fallback-test="window.jQuery"
                        crossorigin="anonymous"
                        integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk"></script>
                <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
                        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
                        crossorigin="anonymous"></script>

                <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                        asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                        asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                        crossorigin="anonymous"
                        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
                </script>
                <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
                        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
                        crossorigin="anonymous"></script>
              
                @*<script src="~/js/site.min.js" asp-append-version="true"></script>*@
            </environment>
        </div>
    </div>
    @RenderSection("Scripts", required: false)
</body>
</html>